schoool-masterV2.0/ViewModels/SchoolClasses/CreateSchoolClassesModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using School.Attributes;

namespace School.ViewModels.SchoolClasses
{//
    public class CreateSchoolClassesModel
    {
        [CustomRequired]
        [Display(Name="Номер класса")]
        public string Name { get; set; }
    }
}

schoool-masterV2.0/ViewModels/SchoolClasses/DeleteSchoolClassesModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using School.Attributes;
using School.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace School.ViewModels.SchoolClasses
{
    public class DeleteSchoolClassesModel
    {//
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

schoool-masterV2.0/ViewModels/SchoolClasses/IndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using School.ViewModels;
using School.Models;


namespace School.ViewModels.SchoolClasses
{
    public class IndexModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<SchoolPupil> Pupils { get; set; }

    }
}

schoool-masterV2.0/Controllers/HomeTasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;
using School.ViewModels.HomeTasks;

namespace School.Controllers
{
    public class HomeTasksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeTasksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: HomeTasks
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Tasks.Include(h => h.Class);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: HomeTasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var homeTask = await _context.Tasks
                .Include(h => h.Class)
                .FirstOrDefaultAsync(m => m.Id == id);           
            if (homeTask == null)
            {
                return NotFound();
            }
           var model = new DetailsHomeTasksModel()
            {
                Subject = homeTask.Subject,
                Content = homeTask.Content,
                Deadline = homeTask.Deadline,
                ClassId = homeTask.ClassId
            };
            return View(model);
        }

        // GET: HomeTasks/Create
        public IActionResult Create(int id)
        {
            var model = new CreateHomeTaskModel {
                ClassId = id
            };
           
            return View(model);
        }

        // POST: HomeTasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateHomeTaskModel model )
        {
            if (ModelState.IsValid)
            {
                var homeTask = new HomeTask {
                    Subject = model.Subject,
                    Content=model.Content,
                    Deadline=model.Deadline,
                    ClassId=model.ClassId
                };
                _context.Add(homeTask);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "SchoolClasses", new { id = model.ClassId });
            }
            model.Tasks = new SelectList(_context.Classes, "Id", "Id", model.ClassId);
            return View(model);
        }



        // GET: HomeTasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var homeTask = await _context.Tasks.FindAsync(id);
            if (homeTask == null)
            {
                return NotFound();
            }
            var model = new EditHomeTasksModel()            
            {
                Id = homeTask.Id,
                Subject = homeTask.Subject,
                Content = homeTask.Content,
                Deadline = homeTask.Deadline,
                ClassId = homeTask.ClassId
               };
            FillEditHomeTaskModel(model, homeTask.ClassId);
            return View(model);
        }

        private void FillEditHomeTaskModel(EditHomeTasksModel model, int classId) 
        {
            
            model.Tasks = new SelectList(_context.Classes, "Id", "Name", classId);
        }

        // POST: HomeTasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditHomeTasksModel model)
        {
            var homeTask = new HomeTask {
            Id = model.Id,
            Subject=model.Subject,
            Content=model.Content,
            Deadline=model.Deadline,
            ClassId=model.ClassId
            };
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(homeTask);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HomeTaskExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            FillEditHomeTaskModel(model, homeTask.ClassId);
            return View(model);
        }

        // GET: HomeTasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var homeTask = await _context.Tasks
                .Include(h => h.Class)
                .FirstOrDefaultAsync(m => m.Id == id);
            
            if (homeTask == null)
            {
                return NotFound();
            }

             DeleteHomeTasksModel model = new DeleteHomeTasksModel
            {
                Id = homeTask.Id,
                Subject = homeTask.Subject,
                Content = homeTask.Content,
                Deadline = homeTask.Deadline,
                ClassId = homeTask.ClassId
            };
            return View(model);
        }

        // POST: HomeTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var homeTask = await _context.Tasks.FindAsync(id);
            _context.Tasks.Remove(homeTask);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HomeTaskExists(int id)
        {
            return _context.Tasks.Any(e => e.Id == id);
        }
    }
}

schoool-masterV2.0/Controllers/SchoolPupilsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;
using Syncfusion.HtmlConverter;
using Syncfusion.Pdf;
using MailKit.Net.Smtp;
using MimeKit;
using School.ViewModels.SchoolPupils;

namespace School.Controllers
{
    public class SchoolPupilsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SchoolPupilsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SchoolPupils
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Pupils.Include(s => s.Class);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: SchoolPupils/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolPupil = await _context.Pupils
                .Include(s => s.Class)
                .FirstOrDefaultAsync(m => m.Id == id);           

            if (schoolPupil == null)
            {
                return NotFound();
            }
            _context.Classes.Load();
            _context.Marks.Load();
            DetailsSchoolPupilsModel model = new DetailsSchoolPupilsModel {
                Id = schoolPupil.Id,
                FirstName = schoolPupil.FirstName,
                MiddleName = schoolPupil.MiddleName,
                LastName = schoolPupil.LastName,
                Email = schoolPupil.Email,
                Address = schoolPupil.Address,
                ClassId = schoolPupil.ClassId,
                Name=schoolPupil.Class.Name,
                Marks = _context.Marks.Where(o => o.PupilId == id)
            .Select(o => new MarksModel
            {
                Id=o.Id,
                LessonDate = o.LessonDate,
                Subject = o.Subject,
                Value = o.Value
            }).ToList()
                //schoolPupil.Marks
            };

            return View(model);
        }

        // GET: SchoolPupils/Create
        public IActionResult Create()
        {
            var model = new CreatePeopleModel
            {
                Classes = new SelectList(_context.Classes, "Id", "Name")
            };

            return View(model);
        }

        // POST: SchoolPupils/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePeopleModel model)
        {
            if (ModelState.IsValid)
            {
                //TODO: Mapper
                var schoolPupil = new SchoolPupil
                {
                    FirstName = model.FirstName,
                    MiddleName = model.MiddleName,
                    LastName = model.LastName,
                    Email = model.Email,
                    Address = model.Address,
                    ClassId = model.ClassId
                };

                //TODO: Business Layer
                _context.Add(schoolPupil);
                await _context.SaveChangesAsync();


                return RedirectToAction(nameof(Index));
            }

            model.Classes = new SelectList(_context.Classes, "Id", "Name");
            return View(model);
        }

        // GET: SchoolPupils/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolPupil = await _context.Pupils.FindAsync(id);
           
            if (schoolPupil == null)
            {
                return NotFound();
            }
            var model = new EditSchoolPupilsModel()
            {
                Id = schoolPupil.Id,
                FirstName = schoolPupil.FirstName,
                MiddleName = schoolPupil.MiddleName,
                LastName = schoolPupil.LastName,
                Email = schoolPupil.Email,
                Address = schoolPupil.Address,
                ClassId = schoolPupil.ClassId
            };
            FillEditSchoolPupilsModel(model, schoolPupil.ClassId);
            return View(model);
        }
        private void FillEditSchoolPupilsModel(EditSchoolPupilsModel model, int classId)
        {

            model.Classes = new SelectList(_context.Classes, "Id", "Name", classId);
        }
        // POST: SchoolPupils/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditSchoolPupilsModel model)
        {
            var schoolPupil = new SchoolPupil {
                Id=model.Id,
                FirstName=model.FirstName,
                MiddleName=model.MiddleName,
                LastName=model.LastName,
                Email=model.Email,
                Address=model.Address,
                ClassId=model.ClassId
            };
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schoolPupil);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolPupilExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            FillEditSchoolPupilsModel(model, schoolPupil.ClassId);
            return View(model);
        }

        // GET: SchoolPupils/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolPupil = await _context.Pupils
                .Include(s => s.Class)
                .FirstOrDefaultAsync(m => m.Id == id);
           
            if (schoolPupil == null)
            {
                return NotFound();
            }
 var model = new DeleteSchoolPupilsModel()
            {
                Id = schoolPupil.Id,
                FirstName = schoolPupil.FirstName,
                MiddleName = schoolPupil.MiddleName,
                LastName = schoolPupil.LastName,
                Email = schoolPupil.Email,
                Address = schoolPupil.Address,
                ClassId = schoolPupil.ClassId
            };
            return View(schoolPupil);
        }

        // POST: SchoolPupils/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var schoolPupil = await _context.Pupils.FindAsync(id);
            _context.Pupils.Remove(schoolPupil);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchoolPupilExists(int id)
        {
            return _context.Pupils.Any(e => e.Id == id);
        }

        public IActionResult Report(int? id, DateTime begin, DateTime end)
        {
            SchoolPupil pupil = _context.Pupils.Include(o=>o.Class).Where(p => p.Id == id).FirstOrDefault();

            if (pupil == null)
            {
                return NotFound();
            }

            var model = new ReportModel {
                Period = string.Format("{0} по {1}", begin.ToShortDateString(), end.ToString("dd-MM-yyyy")),
                FullName = string.Format("{0} {1} {2}", pupil.LastName, pupil.FirstName, pupil.MiddleName),
                ClassName = pupil.Class.Name,
                CurrenDate = DateTime.Now.ToShortDateString(),
                Marks = _context.Marks.Where(o =>
                                o.Pupil.Id == id
                                &&
                                o.LessonDate >= begin
                                &&
                                o.LessonDate <= end)
                            .GroupBy(o => o.Subject)
                            .Select(o => new ReportMarkModel {
                                 Subject = o.Key,
                                Value = o.Average(g => g.Value)
                            }).ToList()
            };

            return View(model);
        }

        public IActionResult Pdf(int? id, DateTime begin, DateTime end)
        {
            HtmlToPdfConverter converter = new HtmlToPdfConverter();
            WebKitConverterSettings settings = new WebKitConverterSettings
            {
                WebKitPath = @"QtBinariesWindows"
            };
            converter.ConverterSettings = settings;

            settings.HttpPostFields.Add("id", id.ToString());
            settings.HttpPostFields.Add("begin", begin.GetDateTimeFormats()[0]);
            settings.HttpPostFields.Add("end", end.GetDateTimeFormats()[0]);

            PdfDocument pdfDocument = converter.Convert("https://localhost:44394/SchoolPupils/Report");

            MemoryStream ms = new MemoryStream();
            pdfDocument.Save(ms);

            ms.Position = 0;

            pdfDocument.Close(true);

            FileStreamResult result = new FileStreamResult(ms, "application/pdf")
            {
                FileDownloadName = "Report.pdf"
            };

            return result;

schoool-masterV2.0/Views/SchoolClasses/Create.cshtml
@model School.ViewModels.SchoolClasses.CreateSchoolClassesModel

@{
    ViewBag.Title = "Create";
}

<h1>Добавление класса</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @Html.DisplayNameFor(o => o.Name)
                @Html.TextAreaFor(o => o.Name, new {@class="form-control"} )
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="SchoolClasses">Cписок классов</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

schoool-masterV2.0/Views/SchoolClasses/Delete.cshtml
@model School.ViewModels.SchoolClasses.DeleteSchoolClassesModel
<!---->
@{
    ViewBag.Title = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SchoolClass</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

schoool-masterV2.0/Views/SchoolClasses/Details.cshtml
@using School.ViewModels.SchoolPupils
@model School.ViewModels.SchoolClasses.DetailsSchoolClassesModel

@{
    ViewBag.Title = Model.Name + " класс";
}


<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#home">Ученики</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#menu1">Задания</a>
    </li>
</ul>

<div class="tab-content">
    <div class="tab-pane container active" id="home">
        <ul class="nav mt-3 mb-3">
            @if (User.Identity.IsAuthenticated)
            {
                <li class="nav-item ml-3">
                    <a asp-action="SendEmail" asp-controller="SchoolClasses" asp-route-id="@Model.Id">
                        Отправить сообщение
                    </a>
                </li>
            }
        </ul>
        <table class="table table-hover text-center">
            <thead>
                <tr>
                    <th>
                        Фамилия
                    </th>
                    <th>
                        Имя
                    </th>
                    <th>
                        Отчество
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pupil in Model.Pupils)
                {
                <tr>
                    <td>
                        @pupil.LastName
                    </td>
                    <td>
                        @pupil.FirstName
                    </td>
                    <td>
                        @pupil.MiddleName
                    </td>
                    <td>
                        <a asp-action="Details" asp-controller="SchoolPupils" asp-route-id="@pupil.Id">
                            Перейти
                        </a>
                    </td>
                    <td>
                        <a asp-action="Edit" asp-controller="SchoolPupils" asp-route-id="@pupil.Id">
                            Edit
                        </a>
                    </td>
                    <td>
                        <a asp-action="Delete" asp-controller="SchoolPupils" asp-route-id="@pupil.Id">
                            Delete
                        </a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="tab-pane container fade" id="menu1">
        <ul class="nav mt-3 mb-3">
            <li class="nav-item">
                @if (User.Identity.IsAuthenticated)
                {
                    <a asp-action="Create" asp-controller="HomeTasks" asp-route-id="@Model.Id">
                        Добавить задание
                    </a>
                }
            </li>
        </ul>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        Дата
                    </th>
                    <th>
                        Предмет
                    </th>
                    <th>
                        Задание
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var taskGroup in Model.Tasks)
                {
                    @foreach (var task in taskGroup)
                    {
                <tr>
                    <td>
                        @taskGroup.Key.ToString("dd-MM-yyyy")
                    </td>
                    <td>
                        @task.Subject
                    </td>
                    <td>
                        @Html.Raw(task.Content)
                    </td>                    
                    <td>
                        <a asp-action="Edit" asp-controller="HomeTasks" asp-route-id="@task.Id">
                            Edit
                        </a>
                    </td>
                    <td>
                        <a asp-action="Delete" asp-controller="HomeTasks" asp-route-id="@task.Id">
                            Delete
                        </a>
                    </td>
                </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<a asp-action="Index" asp-controller="SchoolClasses">
    Cписок классов
</a>

schoool-masterV2.0/Views/SchoolClasses/Edit.cshtml
@model School.ViewModels.SchoolClasses.EditSchoolClassModel

@{
    ViewBag.Title = "Edit";
}

<h1>Edit</h1>

<h4>SchoolClass</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                @Html.DisplayNameFor(o => o.Name)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

schoool-masterV2.0/Views/SchoolClasses/Index.cshtml
@model IEnumerable<School.ViewModels.SchoolClasses.IndexModel>

@{ ViewBag.Title = "Список классов"; }

<h3>Список классов</h3>
@if (User.Identity.IsAuthenticated)
{
<p>
    <a class="btn btn-primary"
       asp-action="Create"
       asp-controller="SchoolClasses">
        Добавить класс
    </a>

    <a class="btn btn-primary"
       asp-action="Create"
       asp-controller="SchoolPupils">
        Добавить ученика
    </a>
</p>
}
<table class="table table-hover text-center">
    <thead>
        <tr>
            <th>
                Класс
            </th>
            <th>
                Учеников
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                <span class="badge badge-primary badge-pill">@(item?.Pupils?.Count ?? 0)</span>
            </td>
            <td>
                <a asp-action="Details" asp-controller="SchoolClasses" asp-route-id="@item.Id">
                    Перейти
                </a>
            </td>
            <td>
                <a asp-action="Delete" asp-controller="SchoolClasses" asp-route-id="@item.Id">
                    Delete
                </a>
            </td>

            <td>
                <a asp-action="Edit" asp-controller="SchoolClasses" asp-route-id="@item.Id">
                    Edit
                </a>
            </td>
        </tr>}
    </tbody>
</table>

schoool-masterV2.0/Views/SchoolClasses/SendEmailForm.cshtml
@using School.ViewModels.SchoolClasses
@model SendEmailFormModel

@{ 
    ViewBag.Title = "Сообщение классу";
}

<div class="row">
    <div class="col-md-4">
        <h4>Сообщение</h4>
        <hr />
        <form method="post" asp-action="SendEmail" asp-controller="SchoolClasses">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input name="id" type="hidden" value="@Model.Id" />
            <div class="form-group">
                <label for="receiver" class="control-label">
                    Получатель
                </label>
                <input id="receiver" type="text" class="form-control" disabled value="@Model.Name" />
            </div>
            <div class="form-group">
                <label for="subject" class="control-label">
                    Тема сообщения
                </label>
                <input id="subject" name="subject" type="text" required class="form-control" pattern="\S.{3,}"/>
            </div>
            <div class="form-group">
                <label for="msg" class="control-label">
                    Текст сообщения
                </label>
                <textarea id="msg" name="msg" required class="form-control" pattern="\S.{5,}"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Отправить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="SchoolClasses" asp-route-id="@Model.Id">
        Профиль класса
    </a>
</div>