schoool-masterV2.0/ViewModels/SchoolPupils/DeleteSchoolPupilsModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using School.Attributes;
using School.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace School.ViewModels.SchoolPupils
{
    public class DeleteSchoolPupilsModel
    {//
        public int Id { get; set; }

        [Display(Name = "Имя")]
        public string FirstName { get; set; }

        [CustomRequired]
        [Display(Name = "Отчество")]
        public string MiddleName { get; set; }

        [CustomRequired]
        [Display(Name = "Фамилия")]
        public string LastName { get; set; }

        [CustomRequired]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [CustomRequired]
        [Display(Name = "Адрес")]
        public string Address { get; set; }
        [Display(Name = "Название класса")]
        public int ClassId { get; set; }
    }
}

schoool-masterV2.0/Controllers/SchoolMarksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;
using School.ViewModels.SchoolMarks;

namespace School.Controllers
{
    public class SchoolMarksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SchoolMarksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SchoolMarks
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Marks.Include(s => s.Pupil);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: SchoolMarks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolMark = await _context.Marks
                .Include(s => s.Pupil)
                .FirstOrDefaultAsync(m => m.Id == id);
            DetailsSchoolMarksModel model = new DetailsSchoolMarksModel
            {
                Id = schoolMark.Id,
                Value = schoolMark.Value,
                Subject = schoolMark.Subject,
                LessonDate = schoolMark.LessonDate,
                LessonOrderNumber = schoolMark.LessonOrderNumber,
                PupilId = schoolMark.PupilId
            };
            if (schoolMark == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: SchoolMarks/Create
        public IActionResult Create(int id)
        {
            var model = new CreateSchoolMarksModel
            {
                PupilId = id
            };
            return View(model);
        }

        // POST: SchoolMarks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( CreateSchoolMarksModel model/*[Bind("")] */)
        {
            if (ModelState.IsValid)
            {
                var schoolMark = new SchoolMark {
                    LessonDate = model.LessonDate,
                    Value= model.Value,
                    Subject= model.Subject,
                    LessonOrderNumber= model.LessonOrderNumber,
                    PupilId= model.PupilId
                };
                _context.Add(schoolMark);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "SchoolPupils", new { id = model.PupilId});
            }
            return View(model);
        }

        // GET: SchoolMarks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolMark = await _context.Marks.FindAsync(id);
            if (schoolMark == null)
            {
                return NotFound();
            }
            var model = new EditSchoolMarksModel()
            {
                Id = schoolMark.Id,
                Value = schoolMark.Value,
                Subject = schoolMark.Subject,
                LessonDate = schoolMark.LessonDate,
                LessonOrderNumber = schoolMark.LessonOrderNumber,
                PupilId = schoolMark.PupilId
            };
            FillEditHomeTaskModel(model, schoolMark.PupilId);
            return View(model);
        }
        private void FillEditHomeTaskModel(EditSchoolMarksModel model, int pupilId)
        {

            model.Marks = new SelectList(_context.Pupils, "Id", "LastName", pupilId);
        }
        // POST: SchoolMarks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditSchoolMarksModel model)
        {
            var schoolMark = new SchoolMark
            {
                Id = model.Id,                
                Value=model.Value,
                Subject=model.Subject,
                LessonDate=model.LessonDate,
                LessonOrderNumber=model.LessonOrderNumber,
                PupilId=model.PupilId
            };
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schoolMark);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolMarkExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            FillEditHomeTaskModel(model, schoolMark.PupilId);
            return View(model);
        }

        // GET: SchoolMarks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolMark = await _context.Marks
                .Include(s => s.Pupil)
                .FirstOrDefaultAsync(m => m.Id == id);
           
            if (schoolMark == null)
            {
                return NotFound();
            }
 var model = new DeleteSchoolMarksModel()
            {
                Id = schoolMark.Id,
                Value = schoolMark.Value,
                Subject = schoolMark.Subject,
                LessonDate = schoolMark.LessonDate,
                LessonOrderNumber = schoolMark.LessonOrderNumber,
                PupilId = schoolMark.PupilId
            };
            return View(model);
        }

        // POST: SchoolMarks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var schoolMark = await _context.Marks.FindAsync(id);
            _context.Marks.Remove(schoolMark);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchoolMarkExists(int id)
        {
            return _context.Marks.Any(e => e.Id == id);
        }
    }
}

schoool-masterV2.0/Controllers/SchoolPupilsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;
using Syncfusion.HtmlConverter;
using Syncfusion.Pdf;
using MailKit.Net.Smtp;
using MimeKit;
using School.ViewModels.SchoolPupils;

namespace School.Controllers
{
    public class SchoolPupilsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SchoolPupilsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SchoolPupils
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Pupils.Include(s => s.Class);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: SchoolPupils/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolPupil = await _context.Pupils
                .Include(s => s.Class)
                .FirstOrDefaultAsync(m => m.Id == id);           

            if (schoolPupil == null)
            {
                return NotFound();
            }
            _context.Classes.Load();
            _context.Marks.Load();
            DetailsSchoolPupilsModel model = new DetailsSchoolPupilsModel {
                Id = schoolPupil.Id,
                FirstName = schoolPupil.FirstName,
                MiddleName = schoolPupil.MiddleName,
                LastName = schoolPupil.LastName,
                Email = schoolPupil.Email,
                Address = schoolPupil.Address,
                ClassId = schoolPupil.ClassId,
                Name=schoolPupil.Class.Name,
                Marks = _context.Marks.Where(o => o.PupilId == id)
            .Select(o => new MarksModel
            {
                Id=o.Id,
                LessonDate = o.LessonDate,
                Subject = o.Subject,
                Value = o.Value
            }).ToList()
                //schoolPupil.Marks
            };

            return View(model);
        }

        // GET: SchoolPupils/Create
        public IActionResult Create()
        {
            var model = new CreatePeopleModel
            {
                Classes = new SelectList(_context.Classes, "Id", "Name")
            };

            return View(model);
        }

        // POST: SchoolPupils/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePeopleModel model)
        {
            if (ModelState.IsValid)
            {
                //TODO: Mapper
                var schoolPupil = new SchoolPupil
                {
                    FirstName = model.FirstName,
                    MiddleName = model.MiddleName,
                    LastName = model.LastName,
                    Email = model.Email,
                    Address = model.Address,
                    ClassId = model.ClassId
                };

                //TODO: Business Layer
                _context.Add(schoolPupil);
                await _context.SaveChangesAsync();


                return RedirectToAction(nameof(Index));
            }

            model.Classes = new SelectList(_context.Classes, "Id", "Name");
            return View(model);
        }

        // GET: SchoolPupils/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolPupil = await _context.Pupils.FindAsync(id);
           
            if (schoolPupil == null)
            {
                return NotFound();
            }
            var model = new EditSchoolPupilsModel()
            {
                Id = schoolPupil.Id,
                FirstName = schoolPupil.FirstName,
                MiddleName = schoolPupil.MiddleName,
                LastName = schoolPupil.LastName,
                Email = schoolPupil.Email,
                Address = schoolPupil.Address,
                ClassId = schoolPupil.ClassId
            };
            FillEditSchoolPupilsModel(model, schoolPupil.ClassId);
            return View(model);
        }
        private void FillEditSchoolPupilsModel(EditSchoolPupilsModel model, int classId)
        {

            model.Classes = new SelectList(_context.Classes, "Id", "Name", classId);
        }
        // POST: SchoolPupils/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditSchoolPupilsModel model)
        {
            var schoolPupil = new SchoolPupil {
                Id=model.Id,
                FirstName=model.FirstName,
                MiddleName=model.MiddleName,
                LastName=model.LastName,
                Email=model.Email,
                Address=model.Address,
                ClassId=model.ClassId
            };
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schoolPupil);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolPupilExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            FillEditSchoolPupilsModel(model, schoolPupil.ClassId);
            return View(model);
        }

        // GET: SchoolPupils/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolPupil = await _context.Pupils
                .Include(s => s.Class)
                .FirstOrDefaultAsync(m => m.Id == id);
           
            if (schoolPupil == null)
            {
                return NotFound();
            }
 var model = new DeleteSchoolPupilsModel()
            {
                Id = schoolPupil.Id,
                FirstName = schoolPupil.FirstName,
                MiddleName = schoolPupil.MiddleName,
                LastName = schoolPupil.LastName,
                Email = schoolPupil.Email,
                Address = schoolPupil.Address,
                ClassId = schoolPupil.ClassId
            };
            return View(schoolPupil);
        }

        // POST: SchoolPupils/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var schoolPupil = await _context.Pupils.FindAsync(id);
            _context.Pupils.Remove(schoolPupil);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchoolPupilExists(int id)
        {
            return _context.Pupils.Any(e => e.Id == id);
        }

        public IActionResult Report(int? id, DateTime begin, DateTime end)
        {
            SchoolPupil pupil = _context.Pupils.Include(o=>o.Class).Where(p => p.Id == id).FirstOrDefault();

            if (pupil == null)
            {
                return NotFound();
            }

            var model = new ReportModel {
                Period = string.Format("{0} по {1}", begin.ToShortDateString(), end.ToString("dd-MM-yyyy")),
                FullName = string.Format("{0} {1} {2}", pupil.LastName, pupil.FirstName, pupil.MiddleName),
                ClassName = pupil.Class.Name,
                CurrenDate = DateTime.Now.ToShortDateString(),
                Marks = _context.Marks.Where(o =>
                                o.Pupil.Id == id
                                &&
                                o.LessonDate >= begin
                                &&
                                o.LessonDate <= end)
                            .GroupBy(o => o.Subject)
                            .Select(o => new ReportMarkModel {
                                 Subject = o.Key,
                                Value = o.Average(g => g.Value)
                            }).ToList()
            };

            return View(model);
        }

        public IActionResult Pdf(int? id, DateTime begin, DateTime end)
        {
            HtmlToPdfConverter converter = new HtmlToPdfConverter();
            WebKitConverterSettings settings = new WebKitConverterSettings
            {
                WebKitPath = @"QtBinariesWindows"
            };
            converter.ConverterSettings = settings;

            settings.HttpPostFields.Add("id", id.ToString());
            settings.HttpPostFields.Add("begin", begin.GetDateTimeFormats()[0]);
            settings.HttpPostFields.Add("end", end.GetDateTimeFormats()[0]);

            PdfDocument pdfDocument = converter.Convert("https://localhost:44394/SchoolPupils/Report");

            MemoryStream ms = new MemoryStream();
            pdfDocument.Save(ms);

            ms.Position = 0;

            pdfDocument.Close(true);

            FileStreamResult result = new FileStreamResult(ms, "application/pdf")
            {
                FileDownloadName = "Report.pdf"
            };

            return result;

schoool-masterV2.0/Views/SchoolPupils/Create.cshtml
@model School.ViewModels.SchoolPupils.CreatePeopleModel
@{
    ViewBag.Title = "Create";
}

<h1>Добавление ученика</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @Html.DisplayNameFor(o => o.FirstName)
                @Html.TextBoxFor(o => o.FirstName, new { @class = "form-control" })
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(o => o.LastName)
                @Html.TextBoxFor(o => o.LastName, new { @class = "form-control" })
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(o => o.MiddleName)
                @Html.TextBoxFor(o => o.MiddleName, new { @class = "form-control" })
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(o => o.Email)
                @Html.TextBoxFor(o => o.Email, new { @class = "form-control" })
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(o => o.Address)
                @Html.TextBoxFor(o => o.Address, new { @class = "form-control" })
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(o => o.ClassId)
                @Html.DropDownListFor(o => o.ClassId, Model.Classes)
            </div>
            <!--                     
               Html.ValidationMessageFor(o => o.Email)        -->
            <div class="form-group">
                <input type="submit" value="Добавить ученика" class="btn btn-primary" />
            </div>
        </form>
</div>
    </div>

    <div>
        <a asp-action="Index" asp-controller="SchoolClasses">
            Cписок классов
        </a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

schoool-masterV2.0/Views/SchoolPupils/Delete.cshtml
@model School.ViewModels.SchoolPupils.DeleteSchoolPupilsModel
<!---->
@{
    ViewBag.Title = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SchoolPupil</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

schoool-masterV2.0/Views/SchoolPupils/Details.cshtml
@model School.ViewModels.SchoolPupils.DetailsSchoolPupilsModel

@{
    ViewBag.Title = "Профиль ученика";
}

<div class="container">
    <h3>@Model.LastName @Model.FirstName @Model.MiddleName</h3>
    <br>
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#home">Данные</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#menu1">Оценки</a>
        </li>
        @if (User.Identity.IsAuthenticated)
        {
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#menu2">Табель</a>
            </li>
        }
    </ul>
    
    <div class="tab-content">
        <div id="home" class="container tab-pane active">
            <br>
            <h4>Контактные данные</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    Класс
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(o => o.Name)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Email)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Address)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Address)
                </dd>
            </dl>
            @if (User.Identity.IsAuthenticated)
            {
                <a class="btn btn-primary" asp-action="SendEmail" asp-controller="SchoolPupils" asp-route-id="@Model.Id">
                    Отправить сообщение
                </a>
            }
        </div>
        <div id="menu1" class="container tab-pane fade">
            <ul class="nav mt-3 mb-3">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="mt-2 mb-2" asp-action="Create" asp-controller="SchoolMarks" asp-route-id="@Model.Id">
                            Добавить отметку
                        </a>
                    </li>
                }
            </ul>
            @if (Model.Marks != null)
            {
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>
                                Предмет
                            </th>
                            <th>
                                Дата
                            </th>
                            <th>
                                Оценка
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Marks.OrderByDescending(p => p.LessonDate))
                        {
                            <tr>
                                <td>
                                    @item.Subject
                                </td>
                                <td>
                                    @item.LessonDate.ToString("yyyy-MM-dd")
                                </td>
                                <td>
                                    @item.Value
                                </td>
                                <td>
                                    <a asp-action="Edit" asp-controller="SchoolMarks" asp-route-id="@item.Id">
                                        Edit
                                    </a>
                                </td>
                                <td>
                                    <a asp-action="Delete" asp-controller="SchoolMarks" asp-route-id="@item.Id">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-success">
                    <strong>Информация об оценках отсутствует!</strong>
                </div>
            }
        </div>
        @if (User.Identity.IsAuthenticated)
        {           
            <div id="menu2" class="container tab-pane fade">
                <form class="mt-4" asp-action="Pdf" asp-controller="SchoolPupils" asp-route-id="@Model.Id">
                    <div class="form-group">
                        <label class="control-label" for="begin">
                            Начало периода
                        </label>
                        <input id="begin" name="begin" type="date" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="end">
                            Конец периода
                        </label>
                        <input id="end" name="end" type="date" class="form-control" />
                    </div>
                    <button class="btn btn-primary">
                        Скачать табель
                    </button>
                </form>
            </div>
        }
        <div class="mt-3">
            <a asp-action="Details" asp-controller="SchoolClasses" asp-route-id="@Model.ClassId">
                Профиль класса
            </a>
        </div>
    </div>
</div>

schoool-masterV2.0/Views/SchoolPupils/Edit.cshtml
@model School.ViewModels.SchoolPupils.EditSchoolPupilsModel

@{
    ViewBag.Title = "Edit";
}

<h1>Edit</h1>

<h4>SchoolPupil</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                @Html.DisplayNameFor(o => o.FirstName)
                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(o => o.MiddleName)
                @Html.TextBoxFor(m => m.MiddleName, new { @class = "form-control" })
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(o => o.LastName)
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(o => o.Email)
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(o => o.Address)
                @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(o => o.ClassId)
                @Html.DropDownListFor(m => m.ClassId, Model.Classes, new { @class = "form-control" })
                <span asp-validation-for="ClassId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

schoool-masterV2.0/Views/SchoolPupils/Index.cshtml
@model IEnumerable<School.Models.SchoolPupil>

@{
    ViewBag.Title = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MiddleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Class)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>